safe: true
permalink: /:title
title: Lost In Permutation
author: Jacob Krall
description: Starting up...
exclude: ['README.md', 'vendor']
twitter: InPermutation
github: InPermutation
linkedin: permutation
stackoverflow: 3140/jacob-krall
youtube: krallja
highlighter: rouge
url: http://jacob.jkrall.net
encoding: utf-8
