safe: true
permalink: /:title
title: Lost In Permutation
author: Jacob Krall
description: Starting up...
exclude: ['README.md']
paginate: 10
gems: [jekyll-paginate]
twitter: InPermutation
github: InPermutation
linkedin: permutation
stackoverflow: 3140/jacob-krall
highlighter: pygments
url: http://jacob.jkrall.net
encoding: utf-8
