safe: true
permalink: /:title
title: Lost In Permutation
author: Jacob Krall
description: Starting up...
exclude: ['README.md']
paginate: 10
twitter: InPermutation
github: InPermutation
linkedin: permutation
stackoverflow: 3140/jacob-krall
pygments: true
url: http://jacob.jkrall.net
